# Starship - Catppuccin Mocha Powerline

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:#cba6f7)\
$os\
$username\
[](fg:#cba6f7 bg:#f38ba8)\
$hostname\
[](fg:#f38ba8 bg:#fab387)\
$directory\
[](fg:#fab387 bg:#a6e3a1)\
$git_branch\
$git_status\
[](fg:#a6e3a1 bg:#89dceb)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$maven\
$nodejs\
$bun\
$nim\
$rust\
$scala\
[](fg:#89dceb bg:#74c7ec)\
$docker_context\
[](fg:#74c7ec bg:#89b4fa)\
$time\
[](fg:#89b4fa)\
$line_break\
 [ ┗━](fg:#cba6f7)\
$character"""

add_newline = true

[username]
show_always = true
style_user = "fg:#1e1e2e bg:#cba6f7"
style_root = "fg:#1e1e2e bg:#cba6f7"
format = '[$user ]($style)'
disabled = false

[hostname]
ssh_only = false
style = "fg:#1e1e2e bg:#f38ba8"
format = '[ $hostname ]($style)'
trim_at = "."
disabled = false

[os]
style = "fg:#1e1e2e bg:#cba6f7"
disabled = true

[directory]
style = "fg:#1e1e2e bg:#fab387"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "fg:#1e1e2e bg:#89dceb"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "fg:#1e1e2e bg:#89dceb"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "fg:#1e1e2e bg:#74c7ec"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "fg:#1e1e2e bg:#89dceb"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:#1e1e2e bg:#89dceb"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:#1e1e2e bg:#a6e3a1"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#1e1e2e bg:#a6e3a1"
format = '[[($all_status$ahead_behind )](fg:#1e1e2e bg:#a6e3a1)]($style)'

[golang]
symbol = " "
style = "fg:#1e1e2e bg:#89dceb"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "fg:#1e1e2e bg:#89dceb"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "fg:#1e1e2e bg:#89dceb"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:#1e1e2e bg:#89dceb"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:#1e1e2e bg:#89dceb"
format = '[ $symbol ($version) ]($style)'

[maven]
style = "fg:#1e1e2e bg:#89dceb"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:#1e1e2e bg:#89dceb"
format = '[ $symbol ($version) ]($style)'

[bun]
symbol = ""
style = "fg:#1e1e2e bg:#89dceb"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "fg:#1e1e2e bg:#89dceb"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#1e1e2e bg:#89dceb"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "fg:#1e1e2e bg:#89dceb"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:#1e1e2e bg:#89b4fa"
format = '[ ♥ $time ]($style)'

[character]
success_symbol = '[▶](bold fg:#cba6f7)'
error_symbol = '[▶](bold fg:#cba6f7)'
vimcmd_symbol = '[❮](bold fg:#a6e3a1)'
vimcmd_replace_one_symbol = '[❮](bold fg:#f9e2af)'
vimcmd_replace_symbol = '[❮](bold fg:#f38ba8)'
vimcmd_visual_symbol = '[❮](bold fg:#cba6f7)'
